apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "dockerconfigjson.name" . }}'
  annotations:
    description: "{{ .Chart.Description }}"
  labels:
    app: '{{ template "dockerconfigjson.name" . }}'
    chart: '{{ template "dockerconfigjson.chart" . }}'
    component: dockerconfigjson
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" . }}
